[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_q3_26 = "6dZ7FPChZqKs14gMpnZtwwSYEUvC8iE5aT2Ay9cf8Mrw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
